<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.AI" Version="10.10.0" />
    <PackageVersion Include="Microsoft.Extensions.AI.Abstractions" Version="10.10.0" />
    <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="10.10.0" />
    <PackageVersion Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.23.2" />
    <PackageVersion Include="Microsoft.ML.OnnxRuntime" Version="1.23.2" />
    <PackageVersion Include="Tokenizers.HuggingFace" Version="3.23.1" />
    <PackageVersion Include="System.Numerics.Tensors" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
